[package]
name = "utility"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leveldb-sys = { path = "leveldb-sys", version = "2.0.10" }
libc = "0.2.*"
