[package]
name = "compress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
zip = "0.6.6"
tar = "0.4.40"
xz2 = "0.1.7"
encoding = "0.2.33"