name: Uncd Assertion binary release

on:
  schedule:
    - cron: '23 */8 * * *'

  workflow_dispatch:
    inputs:
      branch:
        default: 'main'
        description: "Utility branch to build and publish"
        type: string
        required: true

jobs:
  binary-release:
    name: "Build and publish uncd binary"
    runs-on: "ubuntu-latest"
    #environment: deploy
    permissions:
      id-token: write # required to use OIDC authentication

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::875198055600:role/GitHubActionsRunner
          aws-region: us-west-1

      - name: Checkout ${{ github.event.inputs.branch }} branch
        if: ${{ github.event_name == 'workflow_dispatch'}}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout framework repository
        if: ${{ github.event_name != 'workflow_dispatch'}}
        uses: actions/checkout@v4

      - name: Uncd binary build and upload to S3
        run: ./scripts/binary_release.sh assertions-release

      - name: Update latest version metadata in S3
        run: |
          echo $(git rev-parse HEAD) > latest
          BRANCH=$(git branch --show-current)
          aws s3 cp --acl public-read latest s3://unc-oss/$(uname)/${BRANCH}/latest-assertions
